### ISSUE TITLE
Start a public communication forum

### ISSUE THREAD

**Issue by zkoppert** [tektronix/USB-RSA-gnuradio-module-WIP#32]
@kyleb3522 @huddlesd @DStins11 Do you guys have a preferred public communication channel for people to be able to discuss this project? I can help set up accounts at Slack, MS Teams, glitter, etc. if you let me know where you would like it.

https://join.slack.com/t/gr-tekrsa/shared_invite/enQtNzIyOTg1MDg3MDU5LTkzNjg3ZWIxOWQwMmQ2YjU2OTUxNmNjZmVkZmM2ZTRjYzc5MGUyMjhmMjczYzJkZDVjZDA1YWUzOWQ4MWJlNTE

**Comment by DStins11** [comment]
Hi Zack,

I’m not sure what you mean. Give me a call and let’s chat about this.

Thanks,
Dylan
